config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :glossaries
  mount Ckeditor::Engine => '/ckeditor'
  #  resources :documents

  root to: 'visitors#index'
  get 'about', to: 'visitors#about'
  get 'info', to: 'visitors#info'
  get 'search', to: 'documents#search'
  get 'documents', to: 'documents#index'
  resources :narratives

  devise_for :users

  authenticate :user do
    #    resources :documents, only: [:new, :create, :edit, :update, :destroy, :delete]
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  match '*route_not_found', to: 'visitors#index', via: :all
  match '*internal_server_error', to: 'visitors#index', via: :all
end

app/models/glossary.rb
class Glossary < ApplicationRecord
  scope :by_letter, -> (letter) {
    letter ||= 'a'
    where('indigenous_world like ?', "#{letter}%").order('indigenous_word ASC, id ASC')
  }
  validates :indigenous_word, :meaning_pt, presence: true
  validates :indigenous_word, uniqueness: true

  def meaning
    localized_meaning = self["meaning_#{I18n.locale[0, 2]}".to_sym]
    localized_meaning = meaning_pt if localized_meaning.nil?
    localized_meaning
  end

  def attributes
    super.merge(meaning: meaning)
  end
end

app/controllers/glossaries_controller.rb
class GlossariesController < ApplicationController
  before_action :set_glossary, only: [:show, :edit, :update, :destroy]

  # GET /glossaries
  # GET /glossaries.json
  def index
    @glossaries, @alphaParams = Glossary.order(indigenous_word: :asc).alpha_paginate(params[:letter], db_mode: true, db_field: 'indigenous_word')
  end

  # GET /glossaries/1
  # GET /glossaries/1.json
  def show
  end

  # GET /glossaries/new
  def new
    @glossary = Glossary.new
  end

  # GET /glossaries/1/edit
  def edit
  end

  # POST /glossaries
  # POST /glossaries.json
  def create
    @glossary = Glossary.new(glossary_params)

    respond_to do |format|
      if @glossary.save
        format.html { redirect_to @glossary, notice: 'Glossary was successfully created.' }
        format.json { render :show, status: :created, location: @glossary }
      else
        format.html { render :new }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossaries/1
  # PATCH/PUT /glossaries/1.json
  def update
    respond_to do |format|
      if @glossary.update(glossary_params)
        format.html { redirect_to @glossary, notice: 'Glossary was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossary }
      else
        format.html { render :edit }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossaries/1
  # DELETE /glossaries/1.json
  def destroy
    @glossary.destroy
    respond_to do |format|
      format.html { redirect_to glossaries_url, notice: 'Glossary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_glossary
    @glossary = Glossary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def glossary_params
    params.require(:glossary).permit(:letter)
  end
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/views/glossaries/_form.html.erb
<%= form_with(model: glossary, local: true) do |form| %>
  <% if glossary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(glossary.errors.count, "error") %> prohibited this glossary from being saved:</h2>

      <ul>
      <% glossary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :indigenous_word %>
    <%= form.text_field :indigenous_word, id: :glossary_indigenous_word %>
  </div>

  <div class="field">
    <%= form.label :ethnicity %>
    <%= form.text_field :ethnicity, id: :glossary_ethnicity %>
  </div>

  <div class="field">
    <%= form.label :meaning_pt %>
    <%= form.text_field :meaning_pt, id: :glossary_meaning_pt %>
  </div>

  <div class="field">
    <%= form.label :meaning_en %>
    <%= form.text_field :meaning_en, id: :glossary_meaning_en %>
  </div>

  <div class="field">
    <%= form.label :sources %>
    <%= form.text_field :sources, id: :glossary_sources %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/glossaries/edit.html.erb
<h1>Editing Glossary</h1>

<%= render 'form', glossary: @glossary %>

<%= link_to 'Show', @glossary %> |
<%= link_to 'Back', glossaries_path %>

app/views/glossaries/index.html.erb
<% @title = I18n.t('views.glossaries') %>
<div>
  <h1>
    <%= "#{I18n.t('views.glossary')}" %>
  </h1>
</div>
<div class="alpha-pagination">
  <%= alphabetical_paginate @alphaParams %>
</div>
<% if @glossaries.present? %>
  <% @glossaries.each do |glossary| %>
    <div class="document-box">
      <h3><b><%= glossary.indigenous_word %></h3> <i><%= glossary.meaning %></i>
<br><small><%= glossary.sources %></small>
      <hr/>
    </div>
  <% end %>
<% else %>
  <div>
    <% if @none == false %>
      <h2> <%= I18n.t('views.no_glossaries') %> </h2>
    <% end %>
  </div>
<% end %>
<script>
$('.pagination > ul').click(function(e){
  console.log("clicked");
    location.reload()
        e.stopPropagation();
});
</script>

app/views/glossaries/new.html.erb
<h1>New Glossary</h1>

<%= render 'form', glossary: @glossary %>

<%= link_to 'Back', glossaries_path %>

app/views/glossaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Indigenous word:</strong>
  <%= @glossary.indigenous_word %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @glossary.ethnicity %>
</p>

<p>
  <strong>Meaning pt:</strong>
  <%= @glossary.meaning_pt %>
</p>

<p>
  <strong>Meaning en:</strong>
  <%= @glossary.meaning_en %>
</p>

<p>
  <strong>Sources:</strong>
  <%= @glossary.sources %>
</p>

<%= link_to 'Edit', edit_glossary_path(@glossary) %> |
<%= link_to 'Back', glossaries_path %>