config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :glossaries
  mount Ckeditor::Engine => '/ckeditor'
  #  resources :documents

  root to: 'visitors#index'
  get 'about', to: 'visitors#about'
  get 'info', to: 'visitors#info'
  get 'search', to: 'documents#search'
  get 'documents', to: 'documents#index'
  resources :narratives

  devise_for :users

  authenticate :user do
    #    resources :documents, only: [:new, :create, :edit, :update, :destroy, :delete]
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  match '*route_not_found', to: 'visitors#index', via: :all
  match '*internal_server_error', to: 'visitors#index', via: :all
end

app/models/document.rb
class Document < ApplicationRecord
  paginates_per 10
  validates :name, :historical_account, presence: true
  has_attached_file :historical_account
  validates_attachment :historical_account
  validates_attachment_size :historical_account, less_than: 10.megabytes
  validates_attachment_content_type :historical_account, content_type: ['application/pdf', 'application/vnd.ms-excel',
                                                                        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                                                                        'application/msword',
                                                                        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                                                                        'text/plain']

  before_save :extract_text

  def extract_text
    if historical_account.queued_for_write[:original].present?
      my_file = File.read historical_account.queued_for_write[:original].path
      my_file = my_file
      my_content = Henkei.read :text, my_file
      self.content = my_content[0..14519]
     end
  end

  def self.accessible_by(_ability, _action)
    # Instead of a single simple SQL 'WHERE' clause, imagine this accessible_by method can
    # return a variety of different conditions depending on roles the user has.
  end

  searchkick ignore_above: 256
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.order(created_at: :desc).page(params[:page])
  end

  def search
    if params[:keywords].present?
      @none = false
      @keywords = params[:keywords].to_s
      @documents = Document.search params[:keywords], fields: [:ethnicity, :name, :subject, :period, :location, :content, :abstract, :description], page: params[:page], per_page: 10, highlight: { fields: { content: { fragment_size: 20 } }, tag: '<strong>' }
      @results = @documents.total_count
    else
      @none = true
      @documents = Document.order(created_at: :desc).page(params[:page])
      @results = @documents.count
    end
  end

  private

  def document_params
    params.require(:document).permit(:id, :page, :keywords)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/_search_form.html.erb
  <div id="my_search">
    <form role="form" action="/search" id="search_form">
      <h1 class=""><%= t('views.documents') %></h1>
      <small><%= t('views.search_info') %></small>
      <input type="text" class="form-control"  id="search_input" name="keywords" placeholder="">
      <input type="hidden" class="form-control"  id="locale" name="locale" value="<%= I18n.locale %>">
      <br>
      <button class="btn btn-primary" id="search_button" type="submit"><%= t('views.search_go') %></button>
      <br>
    </form>
  </div>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<% @title = I18n.t('views.documents') %>
<div class="container">
  <% if @documents.present? %>
    <div>
      <h1>
        <%= "#{Document.count} #{I18n.t('views.document').pluralize(@documents.count)}" %>
      </h1>
    </div>
    <div>
      <%= paginate @documents %>
    </div>
    <% @documents.each_with_index do |document, i| %>
      <div class="row">
        <hr/>
        <h3>- <%= i+1 %>: <%= link_to document.name, document.historical_account.url unless document.historical_account.url.nil? %></h3>
        <p>  <%= t('views.location') + ": " + document.location.to_s  %></p>
        <p> <%= t('views.ethnicity') + ": " + document.ethnicity.to_s %></p>
        <p> <%= t('views.period') + ": " +  document.period.to_s %></p>
        <p> <%= t('views.abastract') + ": " +  document.abstract.to_s %></p>
        <p> <%= t('views.description') + ": " +  document.description.to_s %></p>
        <hr/>
      </div>
    <% end %>
    <div>
      <%= paginate @documents %>
    </div>
  <% else %>
    <div>
      <% if @none == false %>
        <h2> <%= I18n.t('views.no_documents') %> </h2>
      <% end %>
    </div>
  <% end %>
</div>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/search.html.erb
<% @title = I18n.t('views.documents') %>
<div>
  <%= render "search_form" %>
  <div>
    <h2>
  <% if @keywords.present?  %>
      <%= "\"#{@keywords}\" - #{@results.to_i} #{I18n.t('views.document').pluralize(@results.to_i)}" %>
    <% else  %>
      <%= "#{@documents.total_count} #{I18n.t('views.document').pluralize(@results.to_i)}" %>
    <% end  %>
    </h2>
  </div>
  <% if @documents.present? and @none == false %>
    <div>
      <%= paginate @documents %>
    </div>
    <% @documents.with_details.each do |document, article| %>
      <div class="document-box">
        <h3><%= link_to document.name, document.historical_account.url unless document.historical_account.url.nil? %></h3>
        <p>... <%= (article[:highlight][:content]).to_s.html_safe unless article.empty?  %> ... </p>
        <p><%= t('views.location') + ": " + document.location.to_s  %></p>
        <p><%= t('views.ethnicity') + ": " + document.ethnicity.to_s %></p>
        <p><%= t('views.period') + ": " +  document.period.to_s %></p>
        <p><%= t('views.abstract') + ": " +  document.abstract.to_s %></p>
        <p><%= t('views.description') + ": " +  document.description.to_s %></p>
        <hr>
      </div>
    <% end %>
    <div>
      <%= paginate @documents %>
    </div>
  <% else %>
    <div id="no_result">
      <% if @documents.empty? %>
        <h2> <%= I18n.t('views.no_document') %> </h2>
      <% else%>
        <div>
          <%= paginate @documents %>
        </div>
        <% @documents.each_with_index do |document, i| %>
          <div class="document-box">
            <h3><%= link_to document.name, document.historical_account.url unless document.historical_account.url.nil? %></h3>
            <p><%= t('views.location') + ": " + document.location.to_s  %></p>
            <p><%= t('views.ethnicity') + ": " + document.ethnicity.to_s %></p>
            <p><%= t('views.period') + ": " +  document.period.to_s %></p>
            <p><%= t('views.abstract') + ": " +  document.abstract.to_s %></p>
            <p><%= t('views.description') + ": " +  document.description.to_s %></p>
            <hr>
          </div>
        <% end %>
        <div>
          <%= paginate @documents %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>