config/routes.rb
Rails.application.routes.draw do
  resources :ethnicities
  resources :glossaries
  mount Ckeditor::Engine => '/ckeditor'
  #  resources :documents

  root to: 'visitors#index'
  get 'about', to: 'visitors#about'
  get 'info', to: 'visitors#info'
  get 'search', to: 'documents#search'
  get 'documents', to: 'documents#index'
  resources :narratives

  devise_for :users

  authenticate :user do
    #    resources :documents, only: [:new, :create, :edit, :update, :destroy, :delete]
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  match '*route_not_found', to: 'visitors#index', via: :all
  match '*internal_server_error', to: 'visitors#index', via: :all
end

app/views/layouts/_beautiful_menu.html.erb
<!-- Beautiful Scaffold Menu Do Not Touch This -->
      <li class="<%= "active" if params[:controller] == "places" %>">
        <%= link_to t('app.models.place.bs_caption_plural', :default => 'place').capitalize, places_path %>
      </li>
      <li class="<%= "active" if params[:controller] == "evaluations" %>">
        <%= link_to t('app.models.evaluation.bs_caption_plural', :default => 'evaluation').capitalize, evaluations_path %>
      </li>
<% if user_signed_in? %>
  <li><%= link_to 'My Evaluations', my_index_evaluations_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
  <li><%= link_to 'About', '/about' %></li>

app/views/layouts/_footer.html.erb
<footer>
  <%=link_to( image_tag("fapesb.png"), :class=>"work") %>

</footer>

app/views/layouts/_form_habtm_tag.html.erb
<%#=
  render :partial => "layouts/form_habtm_tag", :locals => {
    :model_class => @document,
    :model_name => "document",
    :plural_model_name => "documents",
    :linked_model_name => "tag",
    :plural_linked_model_name => "tags",
    :namespace_bs => "admin",
    :field_to_search_for_linked_model => "name",
    :f => f
  }
  # Example to put in a _form.html.erb
%>
<% path_namespace = '/' + namespace_bs if not namespace_bs.blank? %>

<div class="form-group">
    <%= f.label plural_linked_model_name.to_sym, t(plural_linked_model_name.to_sym, :default => plural_linked_model_name.capitalize), :class => "control-label" %>
    <div>
        <ul class="bs-tagit" id="<%= model_name %>_<%= linked_model_name %>_ids" name="<%= model_name %>[<%= linked_model_name %>_ids][]" data-url="<%= path_namespace %>/<%= plural_linked_model_name %>/search_and_filter.json" data-param="q[<%= field_to_search_for_linked_model %>_cont]" data-result="caption">
          <% begin %>
            <% for elt in model_class.send(plural_linked_model_name) %>
            <li data-value="<%= elt.id %>"><%= elt.caption %></li>
            <% end %>
          <% rescue %>
          <% end %>
        </ul>
    </div>
</div>

app/views/layouts/_mass_inserting.html.erb
<% model = ("#{(engine.blank? ? '' : "#{engine.camelize}::")}#{model_name.camelize}").constantize %>
<% formparams = [] %>
<% if not namespace.blank? then %>
  <% formparams << namespace %>
<% end %>
<% formparams << model.new %>
<%= form_for formparams, :method => :post, :html => { :class => "well well-small form-inline mass-inserting #{(params[:mass_inserting] ? 'setfocus' : '')}" } do |f| %>
  <%= hidden_field_tag :mass_inserting, true %>
  <% for col in model_columns %>
    <div <%= visible_column(model_name, col, 'inline') %> class="col-<%= col %>">
      <%=
        ar = model.columns_hash[col]
        if not ar.nil? then
          case ar.type
          when :integer then
            if col =~ /.*_id/ then
              f.collection_select((col).to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_eq"].to_i rescue '' end) }, {:class => "form-control"})
            else
              f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col)).capitalize, :class => "form-control")
            end
          when :boolean then
            (
            "<label class='bs-label-ib'>#{f.check_box(col.to_sym, {}, true, false)}#{t(i18n_translate_path(model_name, col)).capitalize}</label>".html_safe
            )
          else
            f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col)).capitalize, :class => "form-control")
          end
        else
          f.collection_select((col + '_id').to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_id_eq"].to_i rescue '' end) }, {:class => "form-control"})
        end
      %>
    </div>
  <% end %>
  <div style="display:inline;">
    <%= f.submit t(:create, :default => "Create"), :class => "btn btn-default", :data => { :disable_with => t(:saving, :default => "Saving...") } %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modal_columns.html.erb
<div class="modal fade" id="modal-columns">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3><%= t(:select_columns, :default => "Select Columns") %></h3>
      </div>
      <div class="modal-body">
        <% for field in model_columns %>
          <label class="checkbox">
            <input type="checkbox" name="field[]" value="<%= field %>" <%= "checked" if session['fields'][model_name.to_s].include?(field) %>> <%= t("app.models.#{model_name}.bs_attributes.#{field}", :default => field.capitalize) %>
          </label><br />
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="filter-columns" data-url="/<%= engine_name %><%= model_name %>/select_fields">Ok</button>
        <button type="button" class="btn btn-default" id="cancel-filter-columns"><%= t(:cancel, :default => "Cancel") %></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'KaririSapuya', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
        <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav fa-ul">
  <li><%= link_to t('views.documents'), search_path %></li>
  <li><%= link_to t('views.narratives'), narratives_path %></li>
  <li><%= link_to t('views.glossary'), glossaries_path %></li>
  <li><%= link_to t('views.ethnicity'), ethnicities_path %></li>
</ul>
<ul class="nav navbar-nav navbar-right fa-ul">
  <li id="item-menu-admin">
    <%= link_to rails_admin_path do %>
      <%= fa_icon "lock", text:"Admin" %>
    <% end %>
  </li>

  <%if @locale_alias != "PT"  %>
    <li class="menu-language">
      <%=  link_to "/", { locale: :"pt-BR" } do 
        fa_icon "language", text: "Em Português"
      end
    %>
  </li>
<% else %>
    <li class="menu-language">
      <%=  link_to "/?locale=en", { locale: :en } do 
        fa_icon "language", text: "English"
      end
    %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Catamaran','application.css' %>
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <% if  @title.present?  %>
      <title><%=  @title +  " - KaririSapuyá" %></title>
    <% else  %>
      <title><%=  "KaririSapuyá" %></title>
    <% end  %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Kariri Sapuya" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-1">
            <b><%= t('views.realization') %>:</b>
          </div>
          <div class="col-md-2">
            <%=link_to( image_tag("ufba.png", size: "80x80"), "http://www.fapesb.ba.gov.br", :target => "_blank" ) %>
          </div>
          <div class="col-md-2">
            <%=link_to( image_tag("pineb.png", size: "160x160"), "http://www.pineb.ffch.ufba.br", :target => "_blank" )%>
          </div>
          <div class="col-md-1">
            <b><%= t('views.support') %>:</b>
          </div>
          <div class="col-md-2">
            <%=link_to( image_tag("fapesb.png", size: "160x80"), "http://www.fapesb.ba.gov.br", :target => "_blank" ) %>
          </div>
        </div>
      </div>
    </footer>
    <script>
$(document).on('click','.navbar-collapse.in',function(e) {
  if( $(e.target).is('a') ) {
    $(this).collapse('hide');
  }
});
    </script>
  </body>
</html>